[workspace]
resolver = "3"
members = [
    "crates/elara-api",
    "crates/elara-bench",
    "crates/elara-bytecode",
    "crates/elara-capi",
    "crates/elara-compiler",
    "crates/elara-core",
    "crates/elara-interp",
    "crates/elara-jit",
    "crates/elara-stdlib",
    "crates/elara-syntax",
    "crates/elara-test",
]

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
version = "0.1.0"

[workspace.dependencies]
elara-api = { path = "crates/elara-api" }
elara-bytecode = { path = "crates/elara-bytecode" }
elara-capi = { path = "crates/elara-capi" }
elara-compiler = { path = "crates/elara-compiler" }
elara-core = { path = "crates/elara-core" }
elara-interp = { path = "crates/elara-interp" }
elara-jit = { path = "crates/elara-jit" }
elara-stdlib = { path = "crates/elara-stdlib" }
elara-syntax = { path = "crates/elara-syntax" }

[workspace.lints.rust]
rust_2018_idioms = { level = "warn", priority = -1 }
unsafe_op_in_unsafe_fn = "deny"
unused_lifetimes = "deny"
unused_qualifications = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
dbg_macro = "deny"
