[package]
name = "elara-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
elara-compiler.workspace = true
elara-core.workspace = true
elara-interp.workspace = true
elara-jit = { workspace = true, optional = true }
elara-stdlib.workspace = true

[features]
default = []
jit = ["dep:elara-jit", "elara-jit/jit"]

[lints]
workspace = true
