use std::{fs, path::PathBuf};

use elara_api::Lua;
use elara_core::Value;

#[test]
fn conformance_language_fixtures() {
    assert_success_fixture("language/return_42.lua", vec![Value::integer(42)]);
    assert_success_fixture("language/control_flow.lua", vec![Value::integer(17)]);
    assert_success_fixture(
        "language/conditional_branches.lua",
        vec![Value::integer(2), Value::integer(5), Value::integer(6)],
    );
    assert_success_fixture(
        "language/numeric_for_negative_step.lua",
        vec![Value::integer(9)],
    );
    assert_success_fixture(
        "language/generic_for_custom_iterator.lua",
        vec![Value::integer(66), Value::integer(3)],
    );
    assert_success_fixture(
        "language/bitwise.lua",
        vec![
            Value::integer(8),
            Value::integer(14),
            Value::integer(6),
            Value::integer(16),
            Value::integer(4),
            Value::integer(0),
            Value::integer(-1),
        ],
    );
    assert_success_fixture(
        "language/comparisons.lua",
        vec![
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(false),
            Value::boolean(false),
        ],
    );
    assert_success_fixture(
        "language/not_truthiness.lua",
        vec![
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(false),
            Value::boolean(false),
            Value::boolean(false),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "language/logical_operators.lua",
        vec![
            Value::boolean(true),
            Value::boolean(true),
            Value::integer(7),
            Value::integer(8),
            Value::boolean(true),
            Value::integer(0),
        ],
    );
    assert_success_fixture(
        "language/length_operator.lua",
        vec![Value::integer(3), Value::integer(3), Value::integer(9)],
    );
    assert_success_fixture("language/long_string_literal.lua", vec![Value::integer(41)]);
    assert_success_fixture("language/long_string_concat.lua", vec![Value::integer(42)]);
    assert_success_fixture(
        "language/numeric_concat.lua",
        vec![
            Value::integer(4),
            Value::integer(49),
            Value::integer(50),
            Value::integer(97),
            Value::integer(98),
        ],
    );
    assert_success_fixture(
        "language/binary_operand_preservation.lua",
        vec![
            Value::integer(13),
            Value::integer(12),
            Value::integer(3),
            Value::integer(2),
            Value::boolean(true),
        ],
    );
    assert_success_fixture("language/varargs.lua", vec![Value::integer(10)]);
    assert_success_fixture(
        "language/table_fields.lua",
        vec![
            Value::integer(10),
            Value::integer(20),
            Value::integer(30),
            Value::integer(40),
            Value::integer(40),
            Value::integer(4),
        ],
    );
    assert_success_fixture(
        "language/table_computed_keys.lua",
        vec![Value::integer(11), Value::integer(20), Value::integer(30)],
    );
    assert_success_fixture(
        "language/closures.lua",
        vec![Value::integer(42), Value::integer(42)],
    );
    assert_success_fixture(
        "language/closure_upvalue_assignment.lua",
        vec![Value::integer(41), Value::integer(41)],
    );
    assert_success_fixture("language/call_statement.lua", vec![Value::integer(42)]);
    assert_success_fixture(
        "language/global_declarations.lua",
        vec![Value::integer(42), Value::integer(42)],
    );
    assert_success_fixture("language/metamethods.lua", vec![Value::integer(42)]);
    assert_success_fixture(
        "language/multiple_return_assignment.lua",
        vec![
            Value::integer(10),
            Value::integer(20),
            Value::integer(1),
            Value::integer(10),
            Value::integer(20),
            Value::integer(10),
            Value::integer(40),
        ],
    );
    assert_success_fixture(
        "language/multiple_return_reassignment.lua",
        vec![Value::integer(10), Value::integer(20), Value::integer(1)],
    );
    assert_success_fixture(
        "language/function_parameters.lua",
        vec![Value::integer(42), Value::integer(7), Value::nil()],
    );
    assert_success_fixture(
        "language/function_parameters_vararg.lua",
        vec![
            Value::integer(5),
            Value::integer(6),
            Value::integer(7),
            Value::integer(2),
        ],
    );
}

#[test]
fn conformance_standard_library_fixtures() {
    assert_success_fixture("stdlib/math_abs.lua", vec![Value::integer(42)]);
    assert_success_fixture("stdlib/math_abs_float.lua", vec![Value::float(2.5)]);
    assert_success_fixture(
        "stdlib/base_table.lua",
        vec![
            Value::integer(110),
            Value::boolean(true),
            Value::boolean(true),
            Value::integer(3),
            Value::integer(2),
            Value::integer(100),
            Value::integer(101),
        ],
    );
    assert_success_fixture(
        "stdlib/base_globals.lua",
        vec![
            Value::boolean(true),
            Value::boolean(true),
            Value::integer(76),
            Value::integer(53),
            Value::integer(53),
            Value::integer(7),
        ],
    );
    assert_success_fixture(
        "stdlib/base_unsupported_surface.lua",
        vec![
            Value::boolean(true),
            Value::integer(115),
            Value::boolean(true),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/base_loading_error_shapes.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(true),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/base_argument_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture("stdlib/base_warn.lua", Vec::new());
    assert_success_fixture(
        "stdlib/base_more_argument_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/base_rawlen.lua",
        vec![Value::integer(3), Value::integer(3)],
    );
    assert_success_fixture("stdlib/base_rawlen_metamethod.lua", vec![Value::integer(3)]);
    assert_success_fixture(
        "stdlib/base_rawlen_empty.lua",
        vec![Value::integer(0), Value::integer(0)],
    );
    assert_success_fixture(
        "stdlib/base_raw_access.lua",
        vec![Value::integer(42), Value::boolean(true), Value::boolean(true)],
    );
    assert_success_fixture(
        "stdlib/base_raw_access_integer_keys.lua",
        vec![
            Value::integer(10),
            Value::integer(30),
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/base_raw_access_metamethod.lua",
        vec![
            Value::boolean(true),
            Value::integer(99),
            Value::boolean(true),
            Value::integer(42),
            Value::integer(42),
        ],
    );
    assert_success_fixture(
        "stdlib/base_rawset_nil.lua",
        vec![Value::boolean(true), Value::boolean(true)],
    );
    assert_success_fixture(
        "stdlib/base_rawset_metamethod.lua",
        vec![
            Value::boolean(true),
            Value::integer(42),
            Value::integer(0),
        ],
    );
    assert_success_fixture(
        "stdlib/base_rawequal_values.lua",
        vec![
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(false),
        ],
    );
    assert_success_fixture(
        "stdlib/base_rawequal_metamethod.lua",
        vec![
            Value::boolean(true),
            Value::boolean(false),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/base_iteration.lua",
        vec![Value::integer(66), Value::integer(42)],
    );
    assert_success_fixture(
        "stdlib/base_ipairs_stops_at_nil.lua",
        vec![Value::integer(1), Value::integer(11)],
    );
    assert_success_fixture(
        "stdlib/base_pairs_metamethod.lua",
        vec![Value::integer(42), Value::boolean(true), Value::boolean(true)],
    );
    assert_success_fixture(
        "stdlib/base_metatable.lua",
        vec![
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/base_metatable_protected_set.lua",
        vec![Value::boolean(false), Value::integer(115)],
    );
    assert_success_fixture(
        "stdlib/base_metatable_protected_marker.lua",
        vec![Value::integer(42), Value::boolean(true)],
    );
    assert_success_fixture(
        "stdlib/base_assert.lua",
        vec![Value::boolean(true), Value::integer(42)],
    );
    assert_success_fixture(
        "stdlib/base_assert_pcall.lua",
        vec![Value::boolean(false), Value::integer(115)],
    );
    assert_success_fixture(
        "stdlib/base_next.lua",
        vec![Value::integer(1), Value::integer(10)],
    );
    assert_success_fixture(
        "stdlib/base_next_after_key.lua",
        vec![Value::integer(2), Value::integer(20)],
    );
    assert_success_fixture("stdlib/base_next_empty.lua", vec![Value::boolean(true)]);
    assert_success_fixture(
        "stdlib/base_conversion.lua",
        vec![
            Value::integer(20),
            Value::integer(3),
            Value::integer(10),
            Value::boolean(true),
            Value::integer(116),
        ],
    );
    assert_success_fixture(
        "stdlib/base_tonumber_radix.lua",
        vec![
            Value::integer(255),
            Value::integer(35),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/base_tonumber_signed_radix.lua",
        vec![Value::integer(-255), Value::integer(5), Value::integer(-35)],
    );
    assert_success_fixture(
        "stdlib/base_tonumber_number.lua",
        vec![Value::integer(12), Value::float(12.5)],
    );
    assert_success_fixture(
        "stdlib/base_tonumber_invalid.lua",
        vec![
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/base_tonumber_standard.lua",
        vec![Value::integer(-12), Value::integer(16), Value::float(3.5)],
    );
    assert_success_fixture(
        "stdlib/base_type_values.lua",
        vec![
            Value::integer(110),
            Value::integer(98),
            Value::integer(110),
            Value::integer(115),
            Value::integer(116),
            Value::integer(102),
        ],
    );
    assert_success_fixture("stdlib/base_type_thread.lua", vec![Value::integer(116)]);
    assert_success_fixture(
        "stdlib/base_tostring.lua",
        vec![
            Value::integer(110),
            Value::integer(3),
            Value::integer(102),
            Value::integer(5),
            Value::integer(45),
            Value::integer(3),
        ],
    );
    assert_success_fixture(
        "stdlib/base_tostring_true.lua",
        vec![
            Value::integer(4),
            Value::integer(116),
            Value::integer(114),
            Value::integer(117),
            Value::integer(101),
        ],
    );
    assert_success_fixture(
        "stdlib/base_tostring_string.lua",
        vec![
            Value::integer(3),
            Value::integer(97),
            Value::integer(98),
            Value::integer(99),
        ],
    );
    assert_success_fixture(
        "stdlib/base_tostring_table.lua",
        vec![Value::integer(116), Value::integer(58)],
    );
    assert_success_fixture(
        "stdlib/base_tostring_thread.lua",
        vec![Value::integer(116), Value::integer(58)],
    );
    assert_success_fixture(
        "stdlib/base_tostring_function.lua",
        vec![Value::integer(102), Value::integer(58)],
    );
    assert_success_fixture(
        "stdlib/base_tostring_float.lua",
        vec![
            Value::integer(4),
            Value::integer(49),
            Value::integer(50),
            Value::integer(46),
            Value::integer(53),
        ],
    );
    assert_success_fixture(
        "stdlib/base_select_multi.lua",
        vec![Value::integer(20), Value::integer(30)],
    );
    assert_success_fixture(
        "stdlib/base_select_negative.lua",
        vec![Value::integer(30)],
    );
    assert_success_fixture(
        "stdlib/base_select_past_end.lua",
        vec![Value::boolean(true), Value::boolean(true)],
    );
    assert_success_fixture(
        "stdlib/base_select_count_empty.lua",
        vec![Value::integer(0)],
    );
    assert_success_fixture(
        "stdlib/base_select_count_values.lua",
        vec![Value::integer(3)],
    );
    assert_success_fixture(
        "stdlib/base_pcall.lua",
        vec![Value::boolean(true), Value::integer(42)],
    );
    assert_success_fixture(
        "stdlib/base_pcall_multi.lua",
        vec![
            Value::boolean(true),
            Value::integer(1),
            Value::nil(),
            Value::integer(3),
        ],
    );
    assert_success_fixture(
        "stdlib/base_pcall_error.lua",
        vec![Value::boolean(false), Value::integer(115)],
    );
    assert_success_fixture(
        "stdlib/base_xpcall.lua",
        vec![Value::boolean(false), Value::integer(9)],
    );
    assert_success_fixture(
        "stdlib/base_xpcall_multi.lua",
        vec![
            Value::boolean(true),
            Value::integer(2),
            Value::nil(),
            Value::integer(4),
        ],
    );
    assert_success_fixture(
        "stdlib/math_string_patterns.lua",
        vec![
            Value::integer(7),
            Value::integer(2),
            Value::integer(2),
            Value::integer(42),
            Value::integer(105),
            Value::integer(4),
            Value::integer(3),
            Value::integer(3),
        ],
    );
    assert_success_fixture(
        "stdlib/string_pattern_captures.lua",
        vec![Value::integer(5), Value::integer(7)],
    );
    assert_success_fixture(
        "stdlib/string_argument_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/string_more_argument_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/string_find_positions.lua",
        vec![Value::integer(4), Value::integer(5)],
    );
    assert_success_fixture(
        "stdlib/string_find_dot_wildcard.lua",
        vec![Value::integer(1), Value::integer(2)],
    );
    assert_success_fixture(
        "stdlib/string_find_bracket_class.lua",
        vec![Value::integer(4), Value::integer(5)],
    );
    assert_success_fixture(
        "stdlib/string_find_negated_bracket_class.lua",
        vec![Value::integer(4), Value::integer(5)],
    );
    assert_success_fixture(
        "stdlib/string_find_quantifiers.lua",
        vec![Value::integer(1), Value::integer(4)],
    );
    assert_success_fixture(
        "stdlib/string_find_optional_quantifier.lua",
        vec![Value::integer(3), Value::integer(4)],
    );
    assert_success_fixture(
        "stdlib/string_find_plain.lua",
        vec![Value::integer(4), Value::integer(4)],
    );
    assert_success_fixture(
        "stdlib/string_find_plain_negative_init.lua",
        vec![Value::integer(5), Value::integer(6)],
    );
    assert_success_fixture(
        "stdlib/string_find_escaped_literal.lua",
        vec![Value::integer(1), Value::integer(2)],
    );
    assert_success_fixture(
        "stdlib/string_find_start_anchor_init.lua",
        vec![Value::integer(2), Value::integer(3)],
    );
    assert_success_fixture(
        "stdlib/string_find_end_anchor.lua",
        vec![Value::integer(5), Value::integer(6)],
    );
    assert_success_fixture(
        "stdlib/string_find_captures.lua",
        vec![
            Value::integer(1),
            Value::integer(6),
            Value::integer(3),
            Value::integer(97),
            Value::integer(3),
            Value::integer(49),
        ],
    );
    assert_success_fixture(
        "stdlib/string_find_frontier.lua",
        vec![Value::integer(5), Value::integer(7)],
    );
    assert_success_fixture(
        "stdlib/string_find_balanced.lua",
        vec![Value::integer(2), Value::integer(8)],
    );
    assert_success_fixture(
        "stdlib/string_find_backreference.lua",
        vec![
            Value::integer(1),
            Value::integer(7),
            Value::integer(3),
            Value::integer(97),
            Value::integer(111),
        ],
    );
    assert_success_fixture(
        "stdlib/string_find_position_captures.lua",
        vec![
            Value::integer(3),
            Value::integer(4),
            Value::integer(3),
            Value::integer(5),
        ],
    );
    assert_success_fixture(
        "stdlib/string_find_missing.lua",
        vec![Value::boolean(true)],
    );
    assert_success_fixture(
        "stdlib/string_position_captures.lua",
        vec![Value::integer(3), Value::integer(5)],
    );
    assert_success_fixture(
        "stdlib/string_match_literal.lua",
        vec![Value::integer(2), Value::integer(99), Value::integer(97)],
    );
    assert_success_fixture(
        "stdlib/string_match_dot_wildcard.lua",
        vec![Value::integer(2), Value::integer(98), Value::integer(99)],
    );
    assert_success_fixture(
        "stdlib/string_match_percent_class.lua",
        vec![Value::integer(2), Value::integer(49), Value::integer(50)],
    );
    assert_success_fixture(
        "stdlib/string_match_escaped_literal.lua",
        vec![Value::integer(2), Value::integer(97), Value::integer(43)],
    );
    assert_success_fixture(
        "stdlib/string_match_bracket_class.lua",
        vec![Value::integer(2), Value::integer(49), Value::integer(50)],
    );
    assert_success_fixture(
        "stdlib/string_match_negated_bracket_class.lua",
        vec![Value::integer(2), Value::integer(49), Value::integer(50)],
    );
    assert_success_fixture(
        "stdlib/string_match_quantifiers.lua",
        vec![Value::integer(4), Value::integer(97), Value::integer(98)],
    );
    assert_success_fixture(
        "stdlib/string_match_optional_quantifier.lua",
        vec![Value::integer(2), Value::integer(97), Value::integer(98)],
    );
    assert_success_fixture(
        "stdlib/string_match_minimal_quantifier.lua",
        vec![Value::integer(2), Value::integer(97), Value::integer(98)],
    );
    assert_success_fixture(
        "stdlib/string_match_start_anchor_init.lua",
        vec![Value::integer(2), Value::integer(98), Value::integer(99)],
    );
    assert_success_fixture(
        "stdlib/string_match_end_anchor.lua",
        vec![Value::integer(2), Value::integer(98), Value::integer(99)],
    );
    assert_success_fixture(
        "stdlib/string_match_captures.lua",
        vec![
            Value::integer(3),
            Value::integer(97),
            Value::integer(3),
            Value::integer(49),
        ],
    );
    assert_success_fixture(
        "stdlib/string_match_balanced.lua",
        vec![Value::integer(7), Value::integer(40), Value::integer(41)],
    );
    assert_success_fixture(
        "stdlib/string_match_frontier.lua",
        vec![Value::integer(3), Value::integer(49), Value::integer(51)],
    );
    assert_success_fixture(
        "stdlib/string_match_backreference.lua",
        vec![Value::integer(3), Value::integer(97), Value::integer(111)],
    );
    assert_success_fixture(
        "stdlib/string_match_init.lua",
        vec![Value::integer(2), Value::integer(98)],
    );
    assert_success_fixture(
        "stdlib/string_match_missing.lua",
        vec![Value::boolean(true)],
    );
    assert_success_fixture(
        "stdlib/string_gsub_literal.lua",
        vec![Value::integer(4), Value::integer(120), Value::integer(120)],
    );
    assert_success_fixture(
        "stdlib/string_gsub_dot_wildcard.lua",
        vec![Value::integer(4), Value::integer(120), Value::integer(120)],
    );
    assert_success_fixture(
        "stdlib/string_gsub_start_anchor.lua",
        vec![Value::integer(5), Value::integer(120), Value::integer(99)],
    );
    assert_success_fixture(
        "stdlib/string_gsub_percent_class.lua",
        vec![Value::integer(4), Value::integer(120), Value::integer(120)],
    );
    assert_success_fixture(
        "stdlib/string_gsub_bracket_class.lua",
        vec![Value::integer(3), Value::integer(120), Value::integer(120)],
    );
    assert_success_fixture(
        "stdlib/string_gsub_quantifiers.lua",
        vec![Value::integer(4), Value::integer(120), Value::integer(98)],
    );
    assert_success_fixture(
        "stdlib/string_gsub_replacement_captures.lua",
        vec![
            Value::integer(16),
            Value::integer(49),
            Value::integer(97),
            Value::integer(37),
        ],
    );
    assert_success_fixture(
        "stdlib/string_gsub_balanced.lua",
        vec![
            Value::integer(3),
            Value::integer(97),
            Value::integer(120),
            Value::integer(101),
        ],
    );
    assert_success_fixture(
        "stdlib/string_gsub_frontier.lua",
        vec![Value::integer(11), Value::integer(110), Value::integer(110)],
    );
    assert_success_fixture(
        "stdlib/string_gsub_backreference.lua",
        vec![
            Value::integer(7),
            Value::integer(100),
            Value::integer(120),
            Value::integer(122),
        ],
    );
    assert_success_fixture(
        "stdlib/string_gsub_numeric_replacement.lua",
        vec![
            Value::integer(4),
            Value::integer(55),
            Value::integer(2),
            Value::integer(8),
            Value::integer(49),
            Value::integer(46),
            Value::integer(53),
            Value::integer(2),
        ],
    );
    assert_success_fixture(
        "stdlib/string_gsub_position_captures.lua",
        vec![
            Value::integer(7),
            Value::integer(49),
            Value::integer(50),
            Value::integer(53),
            Value::integer(54),
        ],
    );
    assert_success_fixture(
        "stdlib/string_gsub_limit.lua",
        vec![Value::integer(120), Value::integer(120), Value::integer(51)],
    );
    assert_success_fixture(
        "stdlib/string_gsub_missing.lua",
        vec![
            Value::integer(3),
            Value::integer(97),
            Value::integer(99),
            Value::integer(0),
        ],
    );
    assert_success_fixture(
        "stdlib/string_gsub_table_replacement.lua",
        vec![
            Value::integer(7),
            Value::integer(119),
            Value::integer(49),
            Value::integer(51),
            Value::integer(1),
        ],
    );
    assert_success_fixture(
        "stdlib/string_gsub_function_replacement.lua",
        vec![
            Value::integer(3),
            Value::integer(65),
            Value::integer(67),
            Value::integer(1),
        ],
    );
    assert_success_fixture(
        "stdlib/string_gsub_nil_false_replacements.lua",
        vec![
            Value::integer(11),
            Value::integer(97),
            Value::integer(100),
            Value::integer(2),
            Value::integer(11),
            Value::integer(97),
            Value::integer(100),
            Value::integer(2),
        ],
    );
    assert_success_fixture(
        "stdlib/string_gmatch_positions.lua",
        vec![
            Value::integer(1),
            Value::integer(3),
            Value::integer(4),
            Value::integer(6),
        ],
    );
    assert_success_fixture(
        "stdlib/string_gmatch_captures.lua",
        vec![
            Value::integer(97),
            Value::integer(1),
            Value::integer(49),
            Value::integer(98),
            Value::integer(2),
            Value::integer(50),
        ],
    );
    assert_success_fixture(
        "stdlib/string_gmatch_percent_class.lua",
        vec![
            Value::integer(1),
            Value::integer(49),
            Value::integer(2),
            Value::integer(50),
        ],
    );
    assert_success_fixture(
        "stdlib/string_gmatch_callable.lua",
        vec![
            Value::integer(1),
            Value::integer(49),
            Value::integer(2),
            Value::integer(50),
            Value::integer(3),
            Value::integer(51),
        ],
    );
    assert_success_fixture(
        "stdlib/string_gmatch_start_anchor.lua",
        vec![
            Value::integer(2),
            Value::integer(94),
            Value::integer(98),
            Value::integer(2),
            Value::integer(94),
            Value::integer(99),
        ],
    );
    assert_success_fixture(
        "stdlib/string_gmatch_empty_matches.lua",
        vec![Value::integer(3)],
    );
    assert_success_fixture("stdlib/string_rep_empty.lua", vec![Value::integer(0)]);
    assert_success_fixture("stdlib/string_rep_negative.lua", vec![Value::integer(0)]);
    assert_success_fixture(
        "stdlib/string_rep_single_separator.lua",
        vec![Value::integer(2), Value::integer(97), Value::integer(98)],
    );
    assert_success_fixture(
        "stdlib/string_rep_separator.lua",
        vec![Value::integer(8), Value::integer(44), Value::integer(44)],
    );
    assert_success_fixture(
        "stdlib/string_reverse_ascii.lua",
        vec![Value::integer(4), Value::integer(100), Value::integer(97)],
    );
    assert_success_fixture("stdlib/string_reverse_empty.lua", vec![Value::integer(0)]);
    assert_success_fixture(
        "stdlib/string_reverse_embedded_nul.lua",
        vec![Value::integer(4), Value::integer(99), Value::integer(97)],
    );
    assert_success_fixture(
        "stdlib/string_sub_default_end.lua",
        vec![Value::integer(2), Value::integer(99), Value::integer(100)],
    );
    assert_success_fixture(
        "stdlib/string_sub_overlong_end.lua",
        vec![Value::integer(2), Value::integer(98), Value::integer(99)],
    );
    assert_success_fixture(
        "stdlib/string_sub_negative_end.lua",
        vec![Value::integer(4), Value::integer(98), Value::integer(101)],
    );
    assert_success_fixture(
        "stdlib/string_sub_negative_start.lua",
        vec![Value::integer(3), Value::integer(100), Value::integer(102)],
    );
    assert_success_fixture(
        "stdlib/string_sub_zero_start.lua",
        vec![Value::integer(2), Value::integer(97), Value::integer(98)],
    );
    assert_success_fixture("stdlib/string_sub_empty.lua", vec![Value::integer(0)]);
    assert_success_fixture(
        "stdlib/string_pattern_advanced.lua",
        vec![Value::integer(7), Value::integer(3)],
    );
    assert_success_fixture(
        "stdlib/string_format.lua",
        vec![
            Value::integer(7),
            Value::integer(48),
            Value::integer(102),
            Value::integer(58),
            Value::integer(43),
        ],
    );
    assert_success_fixture(
        "stdlib/string_format_char.lua",
        vec![
            Value::integer(3),
            Value::integer(65),
            Value::integer(58),
            Value::integer(66),
        ],
    );
    assert_success_fixture(
        "stdlib/string_format_char_pointer_modifiers.lua",
        vec![
            Value::integer(7),
            Value::integer(32),
            Value::integer(65),
            Value::integer(58),
            Value::integer(66),
            Value::integer(17),
            Value::integer(32),
            Value::integer(40),
            Value::integer(58),
            Value::integer(41),
        ],
    );
    assert_success_fixture(
        "stdlib/string_format_float.lua",
        vec![
            Value::integer(9),
            Value::integer(46),
            Value::integer(58),
            Value::integer(43),
        ],
    );
    assert_success_fixture(
        "stdlib/string_format_quote.lua",
        vec![
            Value::integer(4),
            Value::integer(34),
            Value::integer(97),
            Value::integer(98),
            Value::integer(34),
        ],
    );
    assert_success_fixture(
        "stdlib/string_format_quote_scalars.lua",
        vec![
            Value::integer(20),
            Value::integer(110),
            Value::integer(58),
            Value::integer(116),
            Value::integer(58),
            Value::integer(45),
            Value::integer(58),
            Value::integer(49),
        ],
    );
    assert_success_fixture(
        "stdlib/string_format_argument_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/string_format_spec_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/string_format_percent.lua",
        vec![
            Value::integer(5),
            Value::integer(97),
            Value::integer(37),
            Value::integer(98),
            Value::integer(37),
            Value::integer(37),
        ],
    );
    assert_success_fixture(
        "stdlib/string_format_pointer.lua",
        vec![Value::integer(115)],
    );
    assert_success_fixture(
        "stdlib/string_format_long_strings.lua",
        vec![Value::integer(50), Value::integer(107)],
    );
    assert_success_fixture(
        "stdlib/string_format_string_modifiers.lua",
        vec![
            Value::integer(10),
            Value::integer(32),
            Value::integer(32),
            Value::integer(97),
            Value::integer(58),
            Value::integer(32),
            Value::integer(32),
        ],
    );
    assert_success_fixture(
        "stdlib/string_format_integer_modifiers.lua",
        vec![
            Value::integer(9),
            Value::integer(55),
            Value::integer(32),
            Value::integer(32),
            Value::integer(58),
            Value::integer(48),
            Value::integer(55),
        ],
    );
    assert_success_fixture(
        "stdlib/string_format_integer_alternate.lua",
        vec![
            Value::integer(8),
            Value::integer(48),
            Value::integer(120),
            Value::integer(102),
            Value::integer(58),
            Value::integer(48),
            Value::integer(48),
        ],
    );
    assert_success_fixture(
        "stdlib/string_format_signed_flags.lua",
        vec![
            Value::integer(11),
            Value::integer(43),
            Value::integer(58),
            Value::integer(32),
            Value::integer(43),
            Value::integer(48),
            Value::integer(55),
        ],
    );
    assert_success_fixture(
        "stdlib/string_format_integer_precision.lua",
        vec![
            Value::integer(7),
            Value::integer(48),
            Value::integer(55),
            Value::integer(58),
            Value::integer(48),
            Value::integer(97),
        ],
    );
    assert_success_fixture(
        "stdlib/string_len_embedded_nul.lua",
        vec![Value::integer(4), Value::integer(0)],
    );
    assert_success_fixture(
        "stdlib/string_ops.lua",
        vec![
            Value::integer(8),
            Value::integer(4),
            Value::integer(99),
            Value::integer(90),
            Value::integer(97),
        ],
    );
    assert_success_fixture(
        "stdlib/string_case_empty.lua",
        vec![Value::integer(0), Value::integer(0)],
    );
    assert_success_fixture(
        "stdlib/string_case_mapping.lua",
        vec![
            Value::integer(97),
            Value::integer(98),
            Value::integer(99),
            Value::integer(65),
            Value::integer(66),
            Value::integer(67),
        ],
    );
    assert_success_fixture(
        "stdlib/string_case_punctuation.lua",
        vec![
            Value::integer(97),
            Value::integer(45),
            Value::integer(95),
            Value::integer(33),
            Value::integer(65),
            Value::integer(45),
            Value::integer(95),
            Value::integer(33),
        ],
    );
    assert_success_fixture(
        "stdlib/string_byte_char.lua",
        vec![
            Value::integer(3),
            Value::integer(65),
            Value::integer(66),
            Value::integer(67),
            Value::integer(65),
        ],
    );
    assert_success_fixture("stdlib/string_char_empty.lua", vec![Value::integer(0)]);
    assert_success_fixture(
        "stdlib/string_char_embedded_nul.lua",
        vec![Value::integer(3), Value::integer(0)],
    );
    assert_success_fixture(
        "stdlib/string_char_max.lua",
        vec![Value::integer(1), Value::integer(255)],
    );
    assert_success_fixture(
        "stdlib/string_char_range_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/string_byte_out_of_range.lua",
        vec![Value::boolean(true)],
    );
    assert_success_fixture(
        "stdlib/string_byte_default_end.lua",
        vec![Value::integer(90)],
    );
    assert_success_fixture(
        "stdlib/string_byte_overlong_end.lua",
        vec![Value::integer(66)],
    );
    assert_success_fixture(
        "stdlib/string_byte_zero_start.lua",
        Vec::new(),
    );
    assert_success_fixture(
        "stdlib/string_byte_negative_start.lua",
        vec![Value::integer(66)],
    );
    assert_success_fixture(
        "stdlib/string_byte_embedded_nul.lua",
        vec![Value::integer(65), Value::integer(0), Value::integer(67)],
    );
    assert_success_fixture(
        "stdlib/string_byte_empty_range.lua",
        vec![Value::boolean(true), Value::boolean(true)],
    );
    assert_success_fixture(
        "stdlib/string_byte_range.lua",
        vec![Value::integer(66), Value::integer(67)],
    );
    assert_success_fixture(
        "stdlib/math_numeric.lua",
        vec![
            Value::integer(3),
            Value::integer(4),
            Value::float(9.0),
            Value::float(3.0),
            Value::float(8.0),
            Value::integer(12),
            Value::integer(102),
            Value::boolean(false),
        ],
    );
    assert_success_fixture(
        "stdlib/math_integer_rounding.lua",
        vec![Value::integer(9), Value::integer(9)],
    );
    assert_success_fixture("stdlib/math_log_identity.lua", vec![Value::float(0.0)]);
    assert_success_fixture("stdlib/math_log_base10.lua", vec![Value::float(2.0)]);
    assert_success_fixture("stdlib/math_sqrt_zero.lua", vec![Value::float(0.0)]);
    assert_success_fixture(
        "stdlib/math_trig.lua",
        vec![
            Value::float(1.0),
            Value::float(0.0),
            Value::float(180.0),
            Value::float(1.0),
        ],
    );
    assert_success_fixture("stdlib/math_atan_two_arg.lua", vec![Value::integer(1570)]);
    assert_success_fixture(
        "stdlib/math_angle_zero.lua",
        vec![Value::float(0.0), Value::float(0.0)],
    );
    assert_success_fixture(
        "stdlib/math_decompose.lua",
        vec![Value::float(0.75), Value::integer(4)],
    );
    assert_success_fixture(
        "stdlib/math_frexp_zero.lua",
        vec![Value::float(0.0), Value::integer(0)],
    );
    assert_success_fixture("stdlib/math_ldexp_negative.lua", vec![Value::float(0.5)]);
    assert_success_fixture(
        "stdlib/math_modf.lua",
        vec![Value::integer(-3), Value::float(-0.25)],
    );
    assert_success_fixture(
        "stdlib/math_modf_integer.lua",
        vec![Value::integer(5), Value::float(0.0)],
    );
    assert_success_fixture(
        "stdlib/math_nil_results.lua",
        vec![Value::boolean(true), Value::boolean(true), Value::boolean(true)],
    );
    assert_success_fixture(
        "stdlib/math_type_subtypes.lua",
        vec![
            Value::integer(7),
            Value::integer(105),
            Value::integer(114),
            Value::integer(5),
            Value::integer(102),
            Value::integer(116),
        ],
    );
    assert_success_fixture(
        "stdlib/math_type_nil.lua",
        vec![
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/math_constants.lua",
        vec![
            Value::integer(-1),
            Value::integer(102),
            Value::integer(102),
        ],
    );
    assert_success_fixture("stdlib/math_tointeger_float.lua", vec![Value::integer(7)]);
    assert_success_fixture(
        "stdlib/math_tointeger_negative_float.lua",
        vec![Value::integer(-7)],
    );
    assert_success_fixture(
        "stdlib/math_tointeger_integer.lua",
        vec![Value::integer(-12)],
    );
    assert_success_fixture(
        "stdlib/math_tointeger_nil.lua",
        vec![
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/math_minmax_float.lua",
        vec![Value::float(1.5), Value::integer(7)],
    );
    assert_success_fixture(
        "stdlib/math_minmax_integer.lua",
        vec![Value::integer(1), Value::integer(-1)],
    );
    assert_success_fixture(
        "stdlib/math_minmax_single.lua",
        vec![Value::integer(42), Value::float(-7.5)],
    );
    assert_success_fixture("stdlib/math_fmod_negative.lua", vec![Value::integer(-2)]);
    assert_success_fixture("stdlib/math_fmod_float.lua", vec![Value::float(1.5)]);
    assert_success_fixture("stdlib/math_ult_false.lua", vec![Value::boolean(false)]);
    assert_success_fixture("stdlib/math_ult_true.lua", vec![Value::boolean(true)]);
    assert_success_fixture(
        "stdlib/math_random.lua",
        vec![Value::integer(1), Value::integer(7), Value::integer(9)],
    );
    assert_success_fixture(
        "stdlib/math_random_modes.lua",
        vec![Value::integer(102), Value::integer(105), Value::integer(114)],
    );
    assert_success_fixture(
        "stdlib/math_argument_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/math_randomseed_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/math_number_argument_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/math_numeric_function_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/math_more_numeric_function_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/table_string_utf8.lua",
        vec![
            Value::integer(1),
            Value::integer(2),
            Value::integer(3),
            Value::integer(4),
            Value::integer(3),
            Value::integer(2),
            Value::integer(66),
        ],
    );
    assert_success_fixture(
        "stdlib/table_mutation.lua",
        vec![
            Value::integer(5),
            Value::integer(97),
            Value::integer(98),
            Value::integer(20),
            Value::integer(30),
            Value::integer(40),
            Value::integer(40),
            Value::integer(8),
        ],
    );
    assert_success_fixture(
        "stdlib/table_insert_append.lua",
        vec![Value::integer(1), Value::integer(2)],
    );
    assert_success_fixture(
        "stdlib/table_insert_first.lua",
        vec![Value::integer(97), Value::integer(98), Value::integer(99)],
    );
    assert_success_fixture(
        "stdlib/table_insert_position.lua",
        vec![Value::integer(97), Value::integer(98), Value::integer(99)],
    );
    assert_success_fixture("stdlib/table_remove_empty.lua", vec![Value::boolean(true)]);
    assert_success_fixture(
        "stdlib/table_remove_default.lua",
        vec![Value::integer(2), Value::integer(1), Value::boolean(true)],
    );
    assert_success_fixture(
        "stdlib/table_remove_first.lua",
        vec![
            Value::integer(10),
            Value::integer(20),
            Value::integer(30),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/table_remove_position.lua",
        vec![
            Value::integer(20),
            Value::integer(10),
            Value::integer(30),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/table_remove_after_end.lua",
        vec![
            Value::boolean(true),
            Value::integer(1),
            Value::integer(2),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/table_insert_remove_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/table_insert_remove_type_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/table_move_overlap.lua",
        vec![Value::integer(1), Value::integer(1), Value::integer(2)],
    );
    assert_success_fixture(
        "stdlib/table_move_backward_overlap.lua",
        vec![
            Value::boolean(true),
            Value::integer(2),
            Value::integer(3),
            Value::integer(4),
            Value::integer(4),
        ],
    );
    assert_success_fixture(
        "stdlib/table_move_destination.lua",
        vec![
            Value::boolean(true),
            Value::integer(2),
            Value::integer(3),
            Value::integer(1),
            Value::integer(2),
            Value::integer(3),
        ],
    );
    assert_success_fixture(
        "stdlib/table_move_nil_slot.lua",
        vec![
            Value::boolean(true),
            Value::integer(1),
            Value::boolean(true),
            Value::integer(3),
        ],
    );
    assert_success_fixture(
        "stdlib/table_move_empty.lua",
        vec![
            Value::boolean(true),
            Value::integer(1),
            Value::integer(2),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/table_move_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/table_pack_nil.lua",
        vec![
            Value::integer(3),
            Value::integer(1),
            Value::boolean(true),
            Value::integer(3),
        ],
    );
    assert_success_fixture(
        "stdlib/table_pack_empty.lua",
        vec![Value::integer(0), Value::boolean(true)],
    );
    assert_success_fixture(
        "stdlib/table_pack_trailing_nil.lua",
        vec![
            Value::integer(3),
            Value::integer(1),
            Value::integer(2),
            Value::boolean(true),
        ],
    );
    assert_success_fixture("stdlib/table_concat_empty.lua", vec![Value::integer(0)]);
    assert_success_fixture(
        "stdlib/table_concat_default_separator.lua",
        vec![
            Value::integer(3),
            Value::integer(97),
            Value::integer(98),
            Value::integer(99),
        ],
    );
    assert_success_fixture(
        "stdlib/table_concat_default.lua",
        vec![
            Value::integer(5),
            Value::integer(97),
            Value::integer(45),
            Value::integer(99),
        ],
    );
    assert_success_fixture(
        "stdlib/table_concat_explicit_bounds.lua",
        vec![Value::integer(2), Value::integer(98), Value::integer(99)],
    );
    assert_success_fixture(
        "stdlib/table_concat_numbers.lua",
        vec![
            Value::integer(6),
            Value::integer(49),
            Value::integer(124),
            Value::integer(51),
        ],
    );
    assert_success_fixture(
        "stdlib/table_concat_numeric_separator.lua",
        vec![
            Value::integer(5),
            Value::integer(97),
            Value::integer(57),
            Value::integer(99),
        ],
    );
    assert_success_fixture(
        "stdlib/table_concat_nil_separator.lua",
        vec![Value::integer(2), Value::integer(98), Value::integer(99)],
    );
    assert_success_fixture(
        "stdlib/table_concat_long_strings.lua",
        vec![Value::integer(251), Value::integer(33), Value::integer(124)],
    );
    assert_success_fixture(
        "stdlib/table_concat_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/table_operand_type_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/table_ranges.lua",
        vec![
            Value::integer(3),
            Value::integer(98),
            Value::integer(20),
            Value::integer(30),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/table_unpack.lua",
        vec![Value::integer(6), Value::integer(7)],
    );
    assert_success_fixture(
        "stdlib/table_unpack_default_bounds.lua",
        vec![Value::integer(1), Value::integer(2), Value::integer(3)],
    );
    assert_success_fixture(
        "stdlib/table_unpack_nil.lua",
        vec![Value::integer(1), Value::nil(), Value::integer(3)],
    );
    assert_success_fixture(
        "stdlib/table_unpack_non_positive_bounds.lua",
        vec![Value::integer(97), Value::integer(98), Value::integer(99)],
    );
    assert_success_fixture("stdlib/table_unpack_empty.lua", Vec::new());
    assert_success_fixture(
        "stdlib/table_unpack_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/table_sort.lua",
        vec![Value::integer(1), Value::integer(2), Value::integer(3)],
    );
    assert_success_fixture(
        "stdlib/table_sort_strings.lua",
        vec![Value::integer(97), Value::integer(98), Value::integer(99)],
    );
    assert_success_fixture(
        "stdlib/table_sort_long_strings.lua",
        vec![
            Value::integer(97),
            Value::integer(50),
            Value::integer(98),
            Value::integer(50),
        ],
    );
    assert_success_fixture("stdlib/table_sort_single.lua", vec![Value::integer(42)]);
    assert_success_fixture(
        "stdlib/table_sort_comparator.lua",
        vec![Value::integer(2), Value::integer(1)],
    );
    assert_success_fixture(
        "stdlib/table_sort_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/io_stubs.lua",
        vec![
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/io_more_stubs.lua",
        vec![
            Value::boolean(true),
            Value::integer(115),
            Value::boolean(true),
            Value::integer(115),
            Value::boolean(true),
            Value::integer(115),
            Value::boolean(true),
            Value::integer(115),
            Value::boolean(true),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/io_argument_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/io_open_result.lua",
        vec![Value::boolean(true), Value::integer(115)],
    );
    assert_success_fixture(
        "stdlib/io_tmpfile_result.lua",
        vec![Value::boolean(true), Value::integer(115)],
    );
    assert_success_fixture(
        "stdlib/io_write_result.lua",
        vec![Value::boolean(true), Value::integer(115)],
    );
    assert_success_fixture(
        "stdlib/io_flush_result.lua",
        vec![Value::boolean(true), Value::integer(115)],
    );
    assert_success_fixture(
        "stdlib/io_type.lua",
        vec![Value::boolean(true), Value::boolean(true)],
    );
    assert_success_fixture(
        "stdlib/io_type_non_files.lua",
        vec![
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/utf8_iteration.lua",
        vec![
            Value::integer(198),
            Value::integer(3),
            Value::integer(2),
            Value::integer(3),
            Value::integer(91),
        ],
    );
    assert_success_fixture(
        "stdlib/utf8_codes_lax.lua",
        vec![
            Value::integer(1),
            Value::integer(1),
            Value::integer(55296),
        ],
    );
    assert_success_fixture(
        "stdlib/utf8_char.lua",
        vec![Value::integer(1), Value::integer(65)],
    );
    assert_success_fixture(
        "stdlib/utf8_char_multiple_ascii.lua",
        vec![
            Value::integer(3),
            Value::integer(3),
            Value::integer(65),
            Value::integer(66),
            Value::integer(67),
        ],
    );
    assert_success_fixture("stdlib/utf8_char_empty.lua", vec![Value::integer(0)]);
    assert_success_fixture(
        "stdlib/utf8_char_max.lua",
        vec![
            Value::integer(4),
            Value::integer(1),
            Value::integer(1114111),
        ],
    );
    assert_success_fixture("stdlib/utf8_codepoint_empty.lua", Vec::new());
    assert_success_fixture(
        "stdlib/utf8_codepoint_range.lua",
        vec![Value::integer(66), Value::integer(67)],
    );
    assert_success_fixture(
        "stdlib/utf8_codepoint_multibyte_range.lua",
        vec![Value::integer(65), Value::integer(233)],
    );
    assert_success_fixture(
        "stdlib/utf8_codepoint_negative_index.lua",
        vec![Value::integer(233), Value::integer(67)],
    );
    assert_success_fixture(
        "stdlib/utf8_codepoint_lax.lua",
        vec![Value::integer(55296)],
    );
    assert_success_fixture(
        "stdlib/utf8_multibyte.lua",
        vec![
            Value::integer(6),
            Value::integer(2),
            Value::integer(119070),
            Value::integer(3),
        ],
    );
    assert_success_fixture(
        "stdlib/utf8_long_strings.lua",
        vec![
            Value::integer(50),
            Value::integer(50),
            Value::integer(97),
            Value::integer(50),
            Value::integer(50),
        ],
    );
    assert_success_fixture(
        "stdlib/utf8_offset_missing.lua",
        vec![Value::boolean(true)],
    );
    assert_success_fixture(
        "stdlib/utf8_offset_forward_multibyte.lua",
        vec![Value::integer(1), Value::integer(2)],
    );
    assert_success_fixture(
        "stdlib/utf8_offset_four_byte.lua",
        vec![Value::integer(2), Value::integer(5)],
    );
    assert_success_fixture(
        "stdlib/utf8_offset_backward_multibyte.lua",
        vec![Value::integer(3), Value::integer(3)],
    );
    assert_success_fixture(
        "stdlib/utf8_offset_containing.lua",
        vec![Value::integer(2), Value::integer(3)],
    );
    assert_success_fixture("stdlib/utf8_len_empty.lua", vec![Value::integer(0)]);
    assert_success_fixture("stdlib/utf8_len_bounds.lua", vec![Value::integer(2)]);
    assert_success_fixture("stdlib/utf8_len_relative.lua", vec![Value::integer(3)]);
    assert_success_fixture(
        "stdlib/utf8_len_multibyte.lua",
        vec![Value::integer(9), Value::integer(3)],
    );
    assert_success_fixture(
        "stdlib/utf8_len_invalid.lua",
        vec![Value::nil(), Value::integer(2)],
    );
    assert_success_fixture("stdlib/utf8_len_lax.lua", vec![Value::integer(1)]);
    assert_success_fixture(
        "stdlib/utf8_argument_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/utf8_char_range_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/utf8_optional_argument_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/utf8_bounds_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/utf8_codes_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/utf8_invalid_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/os_package_debug.lua",
        vec![
            Value::float(6.0),
            Value::integer(115),
            Value::integer(116),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/package_require.lua",
        vec![
            Value::integer(77),
            Value::integer(77),
            Value::integer(77),
            Value::integer(23),
        ],
    );
    assert_success_fixture(
        "stdlib/package_require_nil_loader.lua",
        vec![Value::boolean(true), Value::boolean(true)],
    );
    assert_success_fixture(
        "stdlib/package_require_custom_searcher.lua",
        vec![Value::integer(80), Value::integer(70), Value::integer(80)],
    );
    assert_success_fixture(
        "stdlib/package_require_loaded_cache.lua",
        vec![Value::integer(123), Value::integer(123), Value::integer(0)],
    );
    assert_success_fixture(
        "stdlib/package_require_false_cache.lua",
        vec![Value::integer(42), Value::integer(42), Value::integer(1)],
    );
    assert_success_fixture(
        "stdlib/package_require_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/package_preload_searcher.lua",
        vec![Value::integer(42)],
    );
    assert_success_fixture(
        "stdlib/package_preload_searcher_data.lua",
        vec![Value::integer(42), Value::integer(58), Value::integer(9)],
    );
    assert_success_fixture(
        "stdlib/package_preload_searcher_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/package_lua_searcher_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/package_searcher_path_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/package_searchpath.lua",
        vec![Value::boolean(true), Value::integer(115)],
    );
    assert_success_fixture(
        "stdlib/package_searchpath_found.lua",
        vec![Value::integer(12), Value::integer(46), Value::integer(67)],
    );
    assert_success_fixture(
        "stdlib/package_searchpath_separators.lua",
        vec![
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/package_searchpath_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/package_config.lua",
        vec![Value::integer(115), Value::integer(10)],
    );
    assert_success_fixture(
        "stdlib/package_default_paths.lua",
        vec![
            Value::integer(115),
            Value::integer(115),
            Value::boolean(false),
            Value::boolean(false),
        ],
    );
    assert_success_fixture(
        "stdlib/package_loadlib.lua",
        vec![
            Value::boolean(true),
            Value::integer(115),
            Value::integer(111),
            Value::integer(4),
        ],
    );
    assert_success_fixture(
        "stdlib/package_loadlib_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/package_c_searchers.lua",
        vec![
            Value::integer(110),
            Value::integer(48),
            Value::integer(110),
            Value::integer(42),
        ],
    );
    assert_success_fixture(
        "stdlib/package_c_searcher_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/debug_introspection.lua",
        vec![
            Value::integer(76),
            Value::integer(0),
            Value::boolean(false),
            Value::integer(109),
            Value::integer(0),
            Value::boolean(false),
            Value::boolean(false),
            Value::integer(0),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/debug_getinfo_options.lua",
        vec![
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(false),
        ],
    );
    assert_success_fixture(
        "stdlib/debug_getinfo_function.lua",
        vec![
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/debug_getinfo_stack_function.lua",
        vec![Value::boolean(true), Value::boolean(true)],
    );
    assert_success_fixture(
        "stdlib/debug_getinfo_currentline.lua",
        vec![
            Value::integer(110),
            Value::boolean(true),
            Value::boolean(true),
            Value::integer(110),
            Value::boolean(true),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/debug_getinfo_active_lines.lua",
        vec![
            Value::integer(116),
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/debug_getinfo_name_transfer.lua",
        vec![
            Value::integer(0),
            Value::boolean(true),
            Value::integer(0),
            Value::integer(0),
            Value::boolean(true),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/debug_getinfo_native_function.lua",
        vec![
            Value::integer(67),
            Value::integer(0),
            Value::integer(0),
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/debug_getinfo_vararg_function.lua",
        vec![Value::integer(1), Value::boolean(true), Value::boolean(true)],
    );
    assert_success_fixture(
        "stdlib/debug_registry.lua",
        vec![Value::integer(42), Value::boolean(true)],
    );
    assert_success_fixture(
        "stdlib/debug_registry_numeric_keys.lua",
        vec![
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/debug_upvalues.lua",
        vec![
            Value::integer(10),
            Value::integer(30),
            Value::integer(40),
            Value::integer(40),
            Value::boolean(false),
            Value::boolean(true),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/debug_getupvalue_name_value.lua",
        vec![Value::integer(120), Value::integer(41), Value::integer(42)],
    );
    assert_success_fixture(
        "stdlib/debug_setupvalue_name_value.lua",
        vec![Value::integer(120), Value::integer(42)],
    );
    assert_success_fixture(
        "stdlib/debug_upvalue_absent.lua",
        vec![
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(false),
            Value::boolean(false),
            Value::boolean(false),
        ],
    );
    assert_success_fixture(
        "stdlib/debug_upvalueid_shared.lua",
        vec![
            Value::boolean(true),
            Value::integer(41),
            Value::integer(41),
        ],
    );
    assert_success_fixture(
        "stdlib/debug_upvalueid_distinct.lua",
        vec![
            Value::boolean(false),
            Value::integer(1),
            Value::integer(2),
        ],
    );
    assert_success_fixture(
        "stdlib/debug_upvaluejoin_return.lua",
        vec![
            Value::boolean(true),
            Value::integer(2),
            Value::integer(2),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/debug_upvalueid_absent.lua",
        vec![
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(false),
            Value::boolean(false),
            Value::boolean(false),
            Value::boolean(false),
            Value::boolean(false),
        ],
    );
    assert_success_fixture(
        "stdlib/debug_locals.lua",
        vec![
            Value::integer(43),
            Value::integer(120),
            Value::integer(120),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/debug_getlocal_stack_absent.lua",
        vec![Value::integer(42), Value::boolean(true)],
    );
    assert_success_fixture(
        "stdlib/debug_function_params.lua",
        vec![Value::integer(97), Value::integer(98), Value::boolean(true)],
    );
    assert_success_fixture(
        "stdlib/debug_setlocal_absent.lua",
        vec![
            Value::integer(1),
            Value::boolean(true),
            Value::boolean(false),
            Value::boolean(false),
            Value::boolean(false),
            Value::boolean(false),
        ],
    );
    assert_success_fixture(
        "stdlib/debug_setlocal_stack_absent.lua",
        vec![Value::integer(1), Value::boolean(true)],
    );
    assert_success_fixture(
        "stdlib/debug_traceback.lua",
        vec![Value::integer(98), Value::integer(115)],
    );
    assert_success_fixture(
        "stdlib/debug_traceback_number.lua",
        vec![
            Value::integer(49),
            Value::integer(50),
            Value::integer(51),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/debug_traceback_message.lua",
        vec![Value::boolean(true)],
    );
    assert_success_fixture(
        "stdlib/debug_argument_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/debug_metatable.lua",
        vec![
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/debug_metatable_clear.lua",
        vec![
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/debug_uservalue.lua",
        vec![Value::boolean(true), Value::boolean(true)],
    );
    assert_success_fixture(
        "stdlib/debug_setuservalue_error.lua",
        vec![Value::boolean(false), Value::integer(115)],
    );
    assert_success_fixture(
        "stdlib/debug_hooks.lua",
        vec![
            Value::boolean(true),
            Value::boolean(true),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/debug_hook_metadata.lua",
        vec![
            Value::boolean(true),
            Value::boolean(true),
            Value::integer(7),
            Value::boolean(true),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/debug_hook_clear_nil.lua",
        vec![Value::boolean(true), Value::boolean(true), Value::boolean(true)],
    );
    assert_success_fixture(
        "stdlib/debug_hook_mask_normalized.lua",
        vec![
            Value::boolean(true),
            Value::integer(3),
            Value::integer(99),
            Value::integer(114),
            Value::integer(108),
            Value::integer(5),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/debug_hook_count_only.lua",
        vec![
            Value::boolean(true),
            Value::integer(0),
            Value::integer(3),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/os_time_date.lua",
        vec![
            Value::integer(1970),
            Value::integer(1),
            Value::integer(1),
            Value::integer(0),
            Value::integer(0),
            Value::integer(0),
            Value::float(86400.0),
            Value::integer(115),
        ],
    );
    assert_success_fixture("stdlib/os_difftime_negative.lua", vec![Value::float(-6.0)]);
    assert_success_fixture(
        "stdlib/os_time_normalize.lua",
        vec![
            Value::integer(31579200),
            Value::integer(1971),
            Value::integer(1),
            Value::integer(1),
            Value::integer(12),
            Value::integer(0),
            Value::integer(0),
        ],
    );
    assert_success_fixture(
        "stdlib/os_time_leap_day.lua",
        vec![
            Value::integer(1709251198),
            Value::integer(2024),
            Value::integer(2),
            Value::integer(29),
            Value::integer(23),
            Value::integer(59),
            Value::integer(58),
        ],
    );
    assert_success_fixture(
        "stdlib/os_time_defaults.lua",
        vec![
            Value::integer(0),
            Value::integer(0),
            Value::integer(0),
            Value::integer(0),
        ],
    );
    assert_success_fixture(
        "stdlib/os_date_format.lua",
        vec![
            Value::integer(19),
            Value::integer(49),
            Value::integer(32),
            Value::integer(48),
        ],
    );
    assert_success_fixture(
        "stdlib/os_date_table_fields.lua",
        vec![Value::integer(5), Value::integer(1), Value::boolean(false)],
    );
    assert_success_fixture(
        "stdlib/os_date_leap_day_table.lua",
        vec![
            Value::integer(2024),
            Value::integer(2),
            Value::integer(29),
            Value::integer(60),
            Value::integer(5),
            Value::integer(23),
            Value::integer(59),
            Value::integer(58),
        ],
    );
    assert_success_fixture(
        "stdlib/os_date_names.lua",
        vec![
            Value::integer(44),
            Value::integer(84),
            Value::integer(84),
            Value::integer(74),
            Value::integer(74),
        ],
    );
    assert_success_fixture(
        "stdlib/os_date_ordinals.lua",
        vec![
            Value::integer(27),
            Value::integer(48),
            Value::integer(52),
            Value::integer(37),
        ],
    );
    assert_success_fixture(
        "stdlib/os_date_composites.lua",
        vec![
            Value::integer(32),
            Value::integer(50),
            Value::integer(48),
            Value::integer(48),
            Value::integer(48),
            Value::integer(45),
            Value::integer(48),
            Value::integer(50),
            Value::integer(45),
            Value::integer(50),
            Value::integer(57),
            Value::integer(32),
            Value::integer(50),
            Value::integer(51),
            Value::integer(58),
            Value::integer(53),
            Value::integer(57),
            Value::integer(58),
            Value::integer(53),
            Value::integer(57),
            Value::integer(32),
            Value::integer(48),
            Value::integer(48),
            Value::integer(32),
            Value::integer(48),
            Value::integer(54),
            Value::integer(48),
            Value::integer(32),
            Value::integer(50),
            Value::integer(32),
            Value::integer(70),
            Value::integer(101),
            Value::integer(98),
        ],
    );
    assert_success_fixture(
        "stdlib/os_date_argument_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
    assert_success_fixture(
        "stdlib/os_locale.lua",
        vec![Value::integer(67), Value::integer(67), Value::boolean(true)],
    );
    assert_success_fixture(
        "stdlib/os_locale_categories.lua",
        vec![
            Value::integer(67),
            Value::integer(67),
            Value::integer(67),
            Value::integer(67),
            Value::integer(67),
            Value::integer(67),
        ],
    );
    assert_success_fixture("stdlib/os_execute.lua", vec![Value::boolean(true)]);
    assert_success_fixture(
        "stdlib/os_execute_status.lua",
        vec![Value::boolean(true), Value::integer(115), Value::integer(0)],
    );
    assert_success_fixture(
        "stdlib/os_execute_failure.lua",
        vec![Value::boolean(true), Value::integer(115), Value::integer(7)],
    );
    assert_success_fixture("stdlib/os_clock.lua", vec![Value::integer(110)]);
    assert_success_fixture("stdlib/os_tmpname.lua", vec![Value::integer(115)]);
    assert_success_fixture("stdlib/os_tmpname_result.lua", vec![Value::integer(115)]);
    assert_success_fixture("stdlib/os_getenv.lua", vec![Value::boolean(true)]);
    assert_success_fixture(
        "stdlib/os_remove.lua",
        vec![
            Value::boolean(true),
            Value::integer(115),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/os_rename.lua",
        vec![
            Value::boolean(true),
            Value::integer(115),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "stdlib/os_argument_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
}

#[test]
fn conformance_error_fixtures() {
    assert_error_fixture("errors/non_callable.lua");
    assert_error_fixture("errors/base_error.lua");
    assert_error_fixture("errors/syntax_unclosed.lua");
    assert_error_fixture("errors/bad_argument.lua");
    assert_error_fixture("errors/non_table_index.lua");
    assert_error_fixture("errors/arithmetic_type.lua");
    assert_error_fixture("errors/debug_uservalue.lua");
    assert_error_fixture("errors/string_format_unsupported.lua");
    assert_error_fixture("errors/string_format_upper_f.lua");
    assert_error_fixture("errors/string_pattern_unsupported.lua");
    assert_error_fixture("errors/string_gsub_invalid_replacement_escape.lua");
    assert_error_fixture("errors/os_exit_unsupported.lua");
    assert_error_fixture("errors/coroutine_yield_outside.lua");
    assert_error_fixture("errors/debug_getinfo_invalid_option.lua");
    assert_error_fixture("errors/coroutine_close_main.lua");
}

#[test]
fn conformance_coroutine_fixtures() {
    assert_success_fixture("coroutine/wrap.lua", vec![Value::integer(42)]);
    assert_success_fixture("coroutine/resume_status.lua", vec![Value::boolean(true)]);
    assert_success_fixture(
        "coroutine/resume_values.lua",
        vec![
            Value::boolean(true),
            Value::integer(42),
            Value::integer(4),
            Value::integer(100),
            Value::nil(),
            Value::integer(22),
            Value::integer(42),
            Value::integer(7),
            Value::integer(119),
        ],
    );
    assert_success_fixture(
        "coroutine/lifecycle.lua",
        vec![
            Value::integer(115),
            Value::boolean(true),
            Value::boolean(true),
            Value::integer(100),
        ],
    );
    assert_success_fixture("coroutine/close.lua", vec![Value::boolean(true)]);
    assert_success_fixture(
        "coroutine/isyieldable.lua",
        vec![
            Value::boolean(false),
            Value::boolean(true),
            Value::boolean(true),
        ],
    );
    assert_success_fixture(
        "coroutine/running.lua",
        vec![Value::integer(116), Value::boolean(true)],
    );
    assert_success_fixture(
        "coroutine/argument_errors.lua",
        vec![
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
            Value::boolean(false),
            Value::integer(115),
        ],
    );
}

fn assert_success_fixture(path: &str, expected: Vec<Value>) {
    assert_success_fixture_values(path, |actual| {
        assert_eq!(actual, expected, "fixture values mismatch for {path}");
    });
}

fn assert_success_fixture_values(path: &str, assert_values: impl FnOnce(Vec<Value>)) {
    let source = fs::read_to_string(fixture_path(path)).expect("fixture should be readable");
    let actual = Lua::new()
        .eval(source)
        .unwrap_or_else(|error| panic!("fixture {path} should succeed: {error:?}"));
    assert_values(actual);
}

fn assert_error_fixture(path: &str) {
    let source = fs::read_to_string(fixture_path(path)).expect("fixture should be readable");
    let result = Lua::new().eval(source);
    assert!(result.is_err(), "fixture {path} should error: {result:?}");
}

fn fixture_path(path: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../tests/conformance")
        .join(path)
}
