use std::{fs, io, path::PathBuf};

use elara_test::{DifferentialRunner, LuaRunner};

const DIFFERENTIAL_FIXTURES: &[&str] = &[
    "language/return_42.lua",
    "language/control_flow.lua",
    "language/bitwise.lua",
    "language/comparisons.lua",
    "language/not_truthiness.lua",
    "language/logical_operators.lua",
    "language/length_operator.lua",
    "language/long_string_literal.lua",
    "language/long_string_concat.lua",
    "language/numeric_concat.lua",
    "language/binary_operand_preservation.lua",
    "language/varargs.lua",
    "language/table_fields.lua",
    "language/closures.lua",
    "language/closure_upvalue_assignment.lua",
    "language/call_statement.lua",
    "language/global_declarations.lua",
    "language/metamethods.lua",
    "language/multiple_return_assignment.lua",
    "language/multiple_return_reassignment.lua",
    "language/function_parameters.lua",
    "language/function_parameters_vararg.lua",
    "stdlib/math_abs.lua",
    "stdlib/math_abs_float.lua",
    "stdlib/base_table.lua",
    "stdlib/base_globals.lua",
    "stdlib/base_loading_error_shapes.lua",
    "stdlib/base_rawlen.lua",
    "stdlib/base_rawlen_empty.lua",
    "stdlib/base_raw_access.lua",
    "stdlib/base_rawset_nil.lua",
    "stdlib/base_rawequal_values.lua",
    "stdlib/base_iteration.lua",
    "stdlib/base_pairs_metamethod.lua",
    "stdlib/base_metatable.lua",
    "stdlib/base_metatable_protected_set.lua",
    "stdlib/base_assert.lua",
    "stdlib/base_assert_pcall.lua",
    "stdlib/base_next.lua",
    "stdlib/base_next_empty.lua",
    "stdlib/base_conversion.lua",
    "stdlib/base_tonumber_radix.lua",
    "stdlib/base_tonumber_number.lua",
    "stdlib/base_tonumber_standard.lua",
    "stdlib/base_type_values.lua",
    "stdlib/base_tostring.lua",
    "stdlib/base_select_multi.lua",
    "stdlib/base_select_count_empty.lua",
    "stdlib/base_pcall.lua",
    "stdlib/base_pcall_error.lua",
    "stdlib/base_xpcall.lua",
    "stdlib/math_string_patterns.lua",
    "stdlib/string_pattern_captures.lua",
    "stdlib/string_find_positions.lua",
    "stdlib/string_find_dot_wildcard.lua",
    "stdlib/string_find_bracket_class.lua",
    "stdlib/string_find_negated_bracket_class.lua",
    "stdlib/string_find_quantifiers.lua",
    "stdlib/string_find_optional_quantifier.lua",
    "stdlib/string_find_plain.lua",
    "stdlib/string_find_escaped_literal.lua",
    "stdlib/string_find_start_anchor_init.lua",
    "stdlib/string_find_end_anchor.lua",
    "stdlib/string_find_captures.lua",
    "stdlib/string_find_frontier.lua",
    "stdlib/string_find_balanced.lua",
    "stdlib/string_find_backreference.lua",
    "stdlib/string_find_position_captures.lua",
    "stdlib/string_find_missing.lua",
    "stdlib/string_position_captures.lua",
    "stdlib/string_match_literal.lua",
    "stdlib/string_match_dot_wildcard.lua",
    "stdlib/string_match_percent_class.lua",
    "stdlib/string_match_escaped_literal.lua",
    "stdlib/string_match_bracket_class.lua",
    "stdlib/string_match_negated_bracket_class.lua",
    "stdlib/string_match_quantifiers.lua",
    "stdlib/string_match_optional_quantifier.lua",
    "stdlib/string_match_minimal_quantifier.lua",
    "stdlib/string_match_start_anchor_init.lua",
    "stdlib/string_match_end_anchor.lua",
    "stdlib/string_match_captures.lua",
    "stdlib/string_match_balanced.lua",
    "stdlib/string_match_frontier.lua",
    "stdlib/string_match_backreference.lua",
    "stdlib/string_match_init.lua",
    "stdlib/string_match_missing.lua",
    "stdlib/string_gsub_literal.lua",
    "stdlib/string_gsub_dot_wildcard.lua",
    "stdlib/string_gsub_start_anchor.lua",
    "stdlib/string_gsub_percent_class.lua",
    "stdlib/string_gsub_bracket_class.lua",
    "stdlib/string_gsub_quantifiers.lua",
    "stdlib/string_gsub_replacement_captures.lua",
    "stdlib/string_gsub_balanced.lua",
    "stdlib/string_gsub_frontier.lua",
    "stdlib/string_gsub_backreference.lua",
    "stdlib/string_gsub_numeric_replacement.lua",
    "stdlib/string_gsub_position_captures.lua",
    "stdlib/string_gsub_limit.lua",
    "stdlib/string_gsub_missing.lua",
    "stdlib/string_gsub_table_replacement.lua",
    "stdlib/string_gsub_function_replacement.lua",
    "stdlib/string_gsub_nil_false_replacements.lua",
    "stdlib/string_gmatch_positions.lua",
    "stdlib/string_gmatch_captures.lua",
    "stdlib/string_gmatch_callable.lua",
    "stdlib/string_gmatch_start_anchor.lua",
    "stdlib/string_gmatch_empty_matches.lua",
    "stdlib/string_rep_empty.lua",
    "stdlib/string_rep_separator.lua",
    "stdlib/string_reverse_empty.lua",
    "stdlib/string_reverse_embedded_nul.lua",
    "stdlib/string_sub_default_end.lua",
    "stdlib/string_sub_negative_end.lua",
    "stdlib/string_sub_empty.lua",
    "stdlib/string_pattern_advanced.lua",
    "stdlib/string_format.lua",
    "stdlib/string_format_char.lua",
    "stdlib/string_format_char_pointer_modifiers.lua",
    "stdlib/string_format_float.lua",
    "stdlib/string_format_quote.lua",
    "stdlib/string_format_quote_scalars.lua",
    "stdlib/string_format_percent.lua",
    "stdlib/string_format_pointer.lua",
    "stdlib/string_format_long_strings.lua",
    "stdlib/string_format_string_modifiers.lua",
    "stdlib/string_format_integer_modifiers.lua",
    "stdlib/string_format_integer_alternate.lua",
    "stdlib/string_format_signed_flags.lua",
    "stdlib/string_format_integer_precision.lua",
    "stdlib/string_len_embedded_nul.lua",
    "stdlib/string_ops.lua",
    "stdlib/string_case_empty.lua",
    "stdlib/string_case_mapping.lua",
    "stdlib/string_byte_char.lua",
    "stdlib/string_char_empty.lua",
    "stdlib/string_char_embedded_nul.lua",
    "stdlib/string_byte_out_of_range.lua",
    "stdlib/string_byte_default_end.lua",
    "stdlib/string_byte_embedded_nul.lua",
    "stdlib/string_byte_range.lua",
    "stdlib/math_numeric.lua",
    "stdlib/math_integer_rounding.lua",
    "stdlib/math_log_identity.lua",
    "stdlib/math_log_base10.lua",
    "stdlib/math_sqrt_zero.lua",
    "stdlib/math_trig.lua",
    "stdlib/math_atan_two_arg.lua",
    "stdlib/math_angle_zero.lua",
    "stdlib/math_decompose.lua",
    "stdlib/math_frexp_zero.lua",
    "stdlib/math_ldexp_negative.lua",
    "stdlib/math_modf.lua",
    "stdlib/math_modf_integer.lua",
    "stdlib/math_nil_results.lua",
    "stdlib/math_type_subtypes.lua",
    "stdlib/math_type_nil.lua",
    "stdlib/math_constants.lua",
    "stdlib/math_tointeger_float.lua",
    "stdlib/math_tointeger_integer.lua",
    "stdlib/math_tointeger_nil.lua",
    "stdlib/math_minmax_float.lua",
    "stdlib/math_fmod_negative.lua",
    "stdlib/math_fmod_float.lua",
    "stdlib/math_ult_false.lua",
    "stdlib/math_ult_true.lua",
    "stdlib/math_random.lua",
    "stdlib/math_random_modes.lua",
    "stdlib/math_argument_errors.lua",
    "stdlib/math_randomseed_errors.lua",
    "stdlib/math_number_argument_errors.lua",
    "stdlib/math_numeric_function_errors.lua",
    "stdlib/table_string_utf8.lua",
    "stdlib/table_mutation.lua",
    "stdlib/table_insert_append.lua",
    "stdlib/table_insert_first.lua",
    "stdlib/table_insert_position.lua",
    "stdlib/table_remove_empty.lua",
    "stdlib/table_remove_default.lua",
    "stdlib/table_remove_first.lua",
    "stdlib/table_remove_position.lua",
    "stdlib/table_insert_remove_errors.lua",
    "stdlib/table_insert_remove_type_errors.lua",
    "stdlib/table_move_overlap.lua",
    "stdlib/table_move_destination.lua",
    "stdlib/table_move_empty.lua",
    "stdlib/table_move_errors.lua",
    "stdlib/table_pack_nil.lua",
    "stdlib/table_pack_empty.lua",
    "stdlib/table_concat_empty.lua",
    "stdlib/table_concat_default_separator.lua",
    "stdlib/table_concat_default.lua",
    "stdlib/table_concat_explicit_bounds.lua",
    "stdlib/table_concat_long_strings.lua",
    "stdlib/table_concat_errors.lua",
    "stdlib/table_operand_type_errors.lua",
    "stdlib/table_ranges.lua",
    "stdlib/table_unpack.lua",
    "stdlib/table_unpack_default_bounds.lua",
    "stdlib/table_unpack_nil.lua",
    "stdlib/table_unpack_empty.lua",
    "stdlib/table_unpack_errors.lua",
    "stdlib/table_sort.lua",
    "stdlib/table_sort_strings.lua",
    "stdlib/table_sort_long_strings.lua",
    "stdlib/table_sort_single.lua",
    "stdlib/table_sort_comparator.lua",
    "stdlib/table_sort_errors.lua",
    "stdlib/io_stubs.lua",
    "stdlib/io_open_result.lua",
    "stdlib/io_tmpfile_result.lua",
    "stdlib/io_write_result.lua",
    "stdlib/io_flush_result.lua",
    "stdlib/io_type.lua",
    "stdlib/utf8_iteration.lua",
    "stdlib/utf8_char.lua",
    "stdlib/utf8_char_empty.lua",
    "stdlib/utf8_char_max.lua",
    "stdlib/utf8_codepoint_empty.lua",
    "stdlib/utf8_codepoint_range.lua",
    "stdlib/utf8_codepoint_multibyte_range.lua",
    "stdlib/utf8_codepoint_lax.lua",
    "stdlib/utf8_multibyte.lua",
    "stdlib/utf8_long_strings.lua",
    "stdlib/utf8_offset_missing.lua",
    "stdlib/utf8_offset_backward_multibyte.lua",
    "stdlib/utf8_offset_containing.lua",
    "stdlib/utf8_len_empty.lua",
    "stdlib/utf8_len_bounds.lua",
    "stdlib/utf8_len_relative.lua",
    "stdlib/utf8_len_invalid.lua",
    "stdlib/utf8_len_lax.lua",
    "stdlib/utf8_argument_errors.lua",
    "stdlib/utf8_bounds_errors.lua",
    "stdlib/utf8_codes_errors.lua",
    "stdlib/utf8_invalid_errors.lua",
    "stdlib/os_package_debug.lua",
    "stdlib/package_require.lua",
    "stdlib/package_require_nil_loader.lua",
    "stdlib/package_require_custom_searcher.lua",
    "stdlib/package_require_errors.lua",
    "stdlib/package_preload_searcher.lua",
    "stdlib/package_preload_searcher_errors.lua",
    "stdlib/package_searchpath.lua",
    "stdlib/package_searchpath_found.lua",
    "stdlib/package_searchpath_separators.lua",
    "stdlib/package_searchpath_errors.lua",
    "stdlib/package_config.lua",
    "stdlib/package_default_paths.lua",
    "stdlib/package_loadlib.lua",
    "stdlib/package_loadlib_errors.lua",
    "stdlib/package_c_searchers.lua",
    "stdlib/debug_introspection.lua",
    "stdlib/debug_getinfo_options.lua",
    "stdlib/debug_registry.lua",
    "stdlib/debug_upvalues.lua",
    "stdlib/debug_upvalue_absent.lua",
    "stdlib/debug_upvalueid_absent.lua",
    "stdlib/debug_locals.lua",
    "stdlib/debug_setlocal_absent.lua",
    "stdlib/debug_traceback.lua",
    "stdlib/debug_traceback_message.lua",
    "stdlib/debug_metatable.lua",
    "stdlib/debug_uservalue.lua",
    "stdlib/debug_setuservalue_error.lua",
    "stdlib/debug_hooks.lua",
    "stdlib/debug_hook_metadata.lua",
    "stdlib/os_time_date.lua",
    "stdlib/os_time_normalize.lua",
    "stdlib/os_time_defaults.lua",
    "stdlib/os_date_format.lua",
    "stdlib/os_date_table_fields.lua",
    "stdlib/os_date_names.lua",
    "stdlib/os_date_ordinals.lua",
    "stdlib/os_date_composites.lua",
    "stdlib/os_locale.lua",
    "stdlib/os_locale_categories.lua",
    "stdlib/os_execute.lua",
    "stdlib/os_execute_status.lua",
    "stdlib/os_execute_failure.lua",
    "stdlib/os_clock.lua",
    "stdlib/os_tmpname.lua",
    "stdlib/os_tmpname_result.lua",
    "stdlib/os_getenv.lua",
    "stdlib/os_remove.lua",
    "stdlib/os_rename.lua",
    "coroutine/wrap.lua",
    "coroutine/resume_status.lua",
    "coroutine/resume_values.lua",
    "coroutine/lifecycle.lua",
    "coroutine/close.lua",
    "coroutine/isyieldable.lua",
    "coroutine/running.lua",
    "errors/non_callable.lua",
    "errors/base_error.lua",
    "errors/syntax_unclosed.lua",
    "errors/bad_argument.lua",
    "errors/non_table_index.lua",
    "errors/arithmetic_type.lua",
    "errors/debug_uservalue.lua",
    "errors/string_format_unsupported.lua",
    "errors/string_format_upper_f.lua",
    "errors/string_pattern_unsupported.lua",
    "errors/string_gsub_invalid_replacement_escape.lua",
    "errors/coroutine_yield_outside.lua",
    "errors/debug_getinfo_invalid_option.lua",
    "errors/coroutine_close_main.lua",
];

#[test]
fn differential_fixtures_match_official_lua_results_when_configured() {
    let Some(official) = LuaRunner::from_env() else {
        eprintln!("skipping differential fixtures; set ELARA_LUA to an official Lua executable");
        return;
    };
    let runner = DifferentialRunner::new(official);

    for fixture in DIFFERENTIAL_FIXTURES {
        if fixture.starts_with("errors/") {
            assert_fixture_class(&runner, fixture).expect("differential fixture should run");
        } else {
            assert_fixture_values(&runner, fixture).expect("differential fixture should run");
        }
    }
}

#[test]
fn differential_fixtures_match_official_lua_error_classes_when_configured() {
    let Some(official) = LuaRunner::from_env() else {
        eprintln!("skipping differential fixtures; set ELARA_LUA to an official Lua executable");
        return;
    };
    let runner = DifferentialRunner::new(official);

    for fixture in DIFFERENTIAL_FIXTURES {
        assert_fixture_class(&runner, fixture).expect("differential fixture should run");
    }
}

fn assert_fixture_values(runner: &DifferentialRunner, path: &str) -> io::Result<()> {
    let source = fs::read_to_string(fixture_path(path))?;
    let comparison = runner.compare_source_values(&source)?;
    assert_eq!(
        comparison.official.class(),
        comparison.elara.class(),
        "fixture {path} differed: official={:?} elara={:?}",
        comparison.official.class(),
        comparison.elara.class()
    );
    assert_eq!(
        comparison.official.stdout, comparison.elara.stdout,
        "fixture {path} returned different values\nofficial stdout:\n{}\nelara stdout:\n{}\nofficial stderr:\n{}\nelara stderr:\n{}",
        comparison.official.stdout,
        comparison.elara.stdout,
        comparison.official.stderr,
        comparison.elara.stderr,
    );
    Ok(())
}

fn assert_fixture_class(runner: &DifferentialRunner, path: &str) -> io::Result<()> {
    let source = fs::read_to_string(fixture_path(path))?;
    let comparison = runner.compare_source(&source)?;
    assert!(
        comparison.same_error_class(),
        "fixture {path} differed: official={:?} elara={:?}",
        comparison.official.class(),
        comparison.elara.class()
    );
    Ok(())
}

fn fixture_path(path: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../tests/conformance")
        .join(path)
}
